# Generated by Django 5.1.7 on 2025-03-24 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="内容")),
                ("amount", models.PositiveIntegerField(verbose_name="金額")),
                (
                    "item_type",
                    models.CharField(
                        choices=[("income", "収入"), ("expense", "支出")],
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="日付")),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="receipts/",
                        verbose_name="レシート画像",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
