# Generated by Django 5.1.7 on 2025-05-12 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="日付"
            ),
        ),
    ]
