# Generated by Django 5.1.7 on 2025-05-20 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_alter_record_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="receipt_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="レシート画像"
            ),
        ),
    ]
